version: 1
disable_existing_loggers: False
formatters:
  default:
    format: '%(asctime)s %(name)s [%(levelname)s] %(message)s'
    datefmt: '%Y/%m/%dT%H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    stream: ext://sys.stdout
  console_err:
    class: logging.StreamHandler
    level: WARNING
    formatter: default
    stream: ext://sys.stderr
  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: default
    when: 'D'
    interval: 1
    backupCount: 10
    filename: 'logs/system_logs.log'
root:
  level: INFO
  handlers: [console, console_err, file]