name: vidiscovery-recognition
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=20.2.4
  - python=3.8.5
  - pymongo=3.11.0
  - pyyaml
  - opencv
  - flask
  - flask-socketio
  - pip:
      - tensorflow_hub
      - tensorflow
      - urllib3
